import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | PAWPower",
  description:
    "Read the PAWPower Terms of Service — the rules and conditions governing your use of our AI-assisted pet health triage platform.",
};

// ─── Section Data ────────────────────────────────────────────────────────────

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: (
      <>
        <p>
          By accessing or using the PAWPower web application and related
          services (collectively, the &ldquo;Service&rdquo;), you agree to be legally bound
          by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to all of
          these Terms, you may not access or use the Service.
        </p>
        <p className="mt-4">
          These Terms constitute a binding legal agreement between you
          (&ldquo;User&rdquo;, &ldquo;you&rdquo;, or &ldquo;your&rdquo;) and PAWPower (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;).
          We reserve the right to update these Terms at any time. Continued use
          of the Service after updates constitutes your acceptance of the
          revised Terms.
        </p>
      </>
    ),
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: (
      <p>
        PAWPower is a digital pet health management platform that provides
        AI-assisted visual triage, geospatial veterinary clinic discovery,
        health record management, vaccination tracking, and care calendar
        features. The Service is intended for informational and organizational
        purposes to assist responsible pet owners in monitoring and managing
        their companion animals&apos; well-being.
      </p>
    ),
  },
  {
    id: "ai-disclaimer",
    title: "3. AI Triage Engine — Important Limitations Disclaimer",
    content: (
      <>
        {/* Prominent Warning Card */}
        <div className="rounded-2xl border border-[var(--state-warning)]/40 bg-[var(--state-warning)]/5 p-5 mb-6">
          <p className="font-semibold text-[var(--text-primary)] mb-2">
            ⚠ Critical Notice — Please Read Carefully
          </p>
          <p className="text-sm text-[var(--text-muted)] leading-relaxed">
            The PAWPower AI Triage Engine is a <strong className="text-[var(--text-primary)]">high-speed guidance and
            diagnostic observation assistant only</strong>. It is{" "}
            <strong className="text-[var(--text-primary)]">NOT</strong> a licensed veterinary
            medical device, a certified clinical diagnostic tool, or a
            replacement for professional veterinary care.
          </p>
        </div>
        <p>
          By using the AI Triage feature, you expressly acknowledge and agree
          to all of the following:
        </p>
        <ul className="mt-4 space-y-3 list-none">
          {[
            {
              label: "Not a Substitute for Professional Care",
              body: "AI triage results, urgency scores, and symptom observations generated by PAWPower are informational guidance only. They do not constitute a clinical diagnosis and must never be used as a substitute for immediate professional veterinary evaluation, emergency veterinary operations, or surgical intervention.",
            },
            {
              label: "No Veterinary-Client-Patient Relationship",
              body: "Use of this Service does not create a veterinary-client-patient relationship (VCPR) between you, your pet, and PAWPower or any person or entity affiliated with PAWPower.",
            },
            {
              label: "Emergency Situations Require Immediate Action",
              body: "If your pet is experiencing a life-threatening emergency — including but not limited to respiratory distress, uncontrolled bleeding, collapse, severe trauma, or suspected poisoning — contact a licensed emergency veterinarian or animal poison control immediately. Do not delay emergency care to obtain an AI triage result.",
            },
            {
              label: "AI Results May Be Inaccurate",
              body: "Machine learning models can produce incorrect, incomplete, or misleading outputs. Triage urgency scores are probabilistic estimates based on visual inputs and are subject to the inherent limitations of computer vision technology, image quality, and available training data.",
            },
            {
              label: "You Retain Full Responsibility",
              body: "All decisions regarding your pet's health, treatment, and veterinary care are entirely your own. PAWPower assumes no liability for decisions made based on AI triage outputs.",
            },
          ].map((item) => (
            <li
              key={item.label}
              className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-base)] px-4 py-3"
            >
              <span className="font-semibold text-[var(--text-primary)]">
                {item.label}:{" "}
              </span>
              <span className="text-[var(--text-muted)]">{item.body}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "eligibility",
    title: "4. Eligibility",
    content: (
      <p>
        You must be at least 18 years of age to create an account and use the
        Service. By registering, you represent and warrant that you are 18 or
        older and have the legal capacity to enter into these Terms. If you are
        accessing the Service on behalf of an organization, you additionally
        represent that you have authority to bind that organization to these
        Terms.
      </p>
    ),
  },
  {
    id: "account",
    title: "5. Account Registration & Security",
    content: (
      <>
        <p>
          You are responsible for maintaining the confidentiality of your
          account credentials and for all activity that occurs under your
          account. You agree to:
        </p>
        <ul className="mt-4 space-y-2 pl-6 list-disc text-[var(--text-muted)]">
          <li>Provide accurate and complete registration information.</li>
          <li>
            Notify us immediately of any unauthorized use of your account.
          </li>
          <li>
            Not share your credentials with any third party or allow others to
            access your account.
          </li>
          <li>
            Maintain one account per user; creating duplicate or fraudulent
            accounts is prohibited.
          </li>
        </ul>
        <p className="mt-4">
          Account authentication is managed by Clerk. PAWPower does not have
          access to your raw password. We may suspend or terminate accounts
          that violate these Terms without prior notice.
        </p>
      </>
    ),
  },
  {
    id: "acceptable-use",
    title: "6. Acceptable Use",
    content: (
      <>
        <p>You agree to use the Service only for lawful purposes. You must not:</p>
        <ul className="mt-4 space-y-2 pl-6 list-disc text-[var(--text-muted)]">
          <li>
            Upload images or content that are illegal, abusive, obscene, or
            violate the rights of any third party.
          </li>
          <li>
            Attempt to reverse-engineer, decompile, or extract any AI model
            weights, algorithms, or proprietary components of the Service.
          </li>
          <li>
            Use automated bots, scrapers, or data-mining tools to access the
            Service without express written permission.
          </li>
          <li>
            Impersonate any person, veterinary professional, or organization.
          </li>
          <li>
            Upload images of humans or non-animal subjects to the triage
            system.
          </li>
          <li>
            Attempt to circumvent, disable, or interfere with security features
            or authentication mechanisms.
          </li>
          <li>
            Use the Service in any manner that could damage, disable,
            overburden, or impair its infrastructure.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "health-records",
    title: "7. Pet Health Data & Records",
    content: (
      <>
        <p>
          You retain full ownership of all pet health records, vaccination logs,
          and care data you enter into the Service. By submitting this data, you
          grant PAWPower a limited, non-exclusive, worldwide, royalty-free
          license to store, process, and display this data solely for the
          purpose of providing the Service to you.
        </p>
        <p className="mt-4">
          We will not sell, license, or disclose your pet health records to
          third parties except as described in our Privacy Policy. You may
          request deletion of your data at any time in accordance with our
          Privacy Policy.
        </p>
      </>
    ),
  },
  {
    id: "intellectual-property",
    title: "8. Intellectual Property",
    content: (
      <p>
        The Service, including its software, AI models, visual design, brand
        identity, text content, and proprietary algorithms, is the exclusive
        intellectual property of PAWPower and is protected by applicable
        copyright, trademark, and trade secret laws. Nothing in these Terms
        grants you any ownership rights in the Service or its components. You
        may not reproduce, distribute, modify, or create derivative works of
        any part of the Service without express written consent.
      </p>
    ),
  },
  {
    id: "third-party",
    title: "9. Third-Party Services",
    content: (
      <p>
        The Service integrates with third-party platforms including Clerk
        (authentication), Supabase (database hosting), and mapping services.
        Your use of these integrations is additionally governed by the
        respective third-party terms of service and privacy policies. PAWPower
        is not responsible for the content, practices, or availability of any
        third-party service.
      </p>
    ),
  },
  {
    id: "disclaimer",
    title: "10. Disclaimer of Warranties",
    content: (
      <>
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES
          OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
          WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
          NON-INFRINGEMENT, OR UNINTERRUPTED AVAILABILITY.
        </p>
        <p className="mt-4">
          We do not warrant that the Service will be error-free, that defects
          will be corrected, or that the Service or its servers are free of
          viruses or other harmful components. We make no warranty regarding the
          accuracy, completeness, or reliability of any AI triage output,
          geolocation result, or health record feature.
        </p>
      </>
    ),
  },
  {
    id: "liability",
    title: "11. Limitation of Liability",
    content: (
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PAWPOWER SHALL NOT
        BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
        PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE,
        INCLUDING BUT NOT LIMITED TO RELIANCE ON AI TRIAGE RESULTS, DELAYED
        VETERINARY CARE, PET INJURY OR DEATH, LOSS OF DATA, OR LOSS OF
        REVENUE. IN NO EVENT SHALL PAWPOWER&apos;S TOTAL AGGREGATE LIABILITY EXCEED
        THE GREATER OF (A) THE AMOUNT YOU PAID FOR THE SERVICE IN THE TWELVE
        MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED US DOLLARS ($100).
      </p>
    ),
  },
  {
    id: "indemnification",
    title: "12. Indemnification",
    content: (
      <p>
        You agree to indemnify, defend, and hold harmless PAWPower and its
        officers, directors, employees, contractors, and agents from and against
        any claims, damages, losses, liabilities, costs, and expenses (including
        reasonable legal fees) arising from your use of the Service, your
        violation of these Terms, or your infringement of any third-party rights.
      </p>
    ),
  },
  {
    id: "termination",
    title: "13. Termination",
    content: (
      <p>
        We reserve the right to suspend or terminate your access to the Service
        at our sole discretion, with or without notice, for conduct that we
        determine violates these Terms or is otherwise harmful to other users,
        the Service, or third parties. Upon termination, your right to use the
        Service ceases immediately. Provisions that by their nature should
        survive termination (including disclaimers, limitations of liability,
        and indemnification) shall continue to apply.
      </p>
    ),
  },
  {
    id: "governing-law",
    title: "14. Governing Law & Disputes",
    content: (
      <p>
        These Terms shall be governed by and construed in accordance with
        applicable law. Any disputes arising from these Terms or the Service
        shall first be attempted to be resolved through good-faith negotiation.
        If unresolved, disputes shall be submitted to binding arbitration or
        the jurisdiction of competent courts as applicable. You waive any right
        to a jury trial and agree not to participate in class action litigation
        against PAWPower.
      </p>
    ),
  },
  {
    id: "contact",
    title: "15. Contact",
    content: (
      <p>
        For questions, notices, or legal inquiries regarding these Terms, please
        contact us at{" "}
        <a
          href="mailto:legal@pawpower.app"
          className="text-[var(--accent-primary)] underline underline-offset-2 hover:opacity-80 transition-opacity"
        >
          legal@pawpower.app
        </a>
        . For account or feature support, use the in-app help system or visit
        our support page.
      </p>
    ),
  },
];

// ─── Page ────────────────────────────────────────────────────────────────────

export default function TermsOfServicePage() {
  const lastUpdated = "July 9, 2026";

  return (
    <main className="min-h-screen bg-[var(--bg-base)] px-4 py-12 sm:px-6 lg:px-8">
      {/* ── Document Card ──────────────────────────────────────────────── */}
      <div className="max-w-3xl mx-auto">
        <article className="rounded-2xl border border-[var(--border-default)] bg-[var(--bg-surface)] p-8 shadow-sm sm:p-10">

          {/* ── Header ─────────────────────────────────────────────────── */}
          <header className="mb-8">
            <p className="mb-3 text-xs font-semibold uppercase tracking-widest text-[var(--accent-primary)]">
              Legal
            </p>
            <h1 className="font-serif text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
              Terms of Service
            </h1>
            <p className="mt-3 text-sm text-[var(--text-muted)]">
              Last Updated:{" "}
              <time dateTime="2026-07-09">{lastUpdated}</time>
            </p>
            <p className="mt-5 leading-relaxed text-[var(--text-muted)]">
              These Terms govern your access to and use of the PAWPower
              platform. Please read them carefully before using the Service.
              Your use of PAWPower constitutes your agreement to these Terms in
              their entirety.
            </p>
          </header>

          <hr className="border-[var(--border-default)]" />

          {/* ── Sections ───────────────────────────────────────────────── */}
          <div className="mt-8 space-y-10">
            {sections.map((section, index) => (
              <section key={section.id} id={section.id}>
                <h2 className="font-serif text-xl font-bold text-[var(--text-primary)] sm:text-2xl">
                  {section.title}
                </h2>
                <div className="mt-4 font-sans text-[var(--text-muted)] leading-relaxed text-sm sm:text-base">
                  {section.content}
                </div>
                {index < sections.length - 1 && (
                  <hr className="mt-10 border-[var(--border-default)]" />
                )}
              </section>
            ))}
          </div>

          {/* ── Footer Nav ─────────────────────────────────────────────── */}
          <div className="mt-12 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between border-t border-[var(--border-default)] pt-8">
            <p className="text-xs text-[var(--text-muted)]">
              &copy; {new Date().getFullYear()} PAWPower. All rights reserved.
            </p>
            <div className="flex gap-4 text-xs">
              <Link
                href="/privacy"
                className="text-[var(--text-muted)] hover:text-[var(--accent-primary)] transition-colors underline underline-offset-2"
              >
                Privacy Policy
              </Link>
              <Link
                href="/"
                className="text-[var(--text-muted)] hover:text-[var(--accent-primary)] transition-colors underline underline-offset-2"
              >
                Back to Home
              </Link>
            </div>
          </div>
        </article>
      </div>
    </main>
  );
}
